name: Test 1

on:
  push:
    branches: [ "main" ]

jobs:

  download:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare loop device
        run: DEVICE=$(losetup -f) && \
          echo "-- $DEVICE --"
